-- 000013_add_upi_id_to_shops.up.sql
ALTER TABLE shops ADD COLUMN IF NOT EXISTS upi_id VARCHAR(100) DEFAULT '';
ALTER TABLE shops ADD COLUMN IF NOT EXISTS opening_time VARCHAR(10) DEFAULT '09:00';
ALTER TABLE shops ADD COLUMN IF NOT EXISTS closing_time VARCHAR(10) DEFAULT '21:00';
ALTER TABLE shops ADD COLUMN IF NOT EXISTS weekly_off VARCHAR(20) DEFAULT '';
ALTER TABLE shops ALTER COLUMN phone DROP NOT NULL;
ALTER TABLE shops ALTER COLUMN pincode DROP NOT NULL;
ALTER TABLE shops ALTER COLUMN city DROP NOT NULL;
