/**
 * Unified Image URL Resolver
 * 
 * Hinglish Hint:
 * Yeh helper backend ya Cloudflare R2 se aane wali image URLs ko fix karta hai:
 * 1. Agar R2 ka private S3 link hai (jo browser me 400/403 deta hai),
 *    toh yeh usse backend ke public streaming endpoint (/images/...) se route karta hai.
 * 2. Relative URLs (/images/...) me API_BASE_URL jodta hai.
 * 3. Local preview (blob: / data:) ko waise hi chalne deta hai.
 */

import { API_BASE_URL } from '../api/client';

export const getImageUrl = (url) => {
  if (!url || typeof url !== 'string') return '';
  const trimmed = url.trim();
  if (!trimmed) return '';

  // Local object URLs or base64 data
  if (trimmed.startsWith('blob:') || trimmed.startsWith('data:')) {
    return trimmed;
  }

  // Cloudflare R2 raw S3 endpoints (e.g., *.r2.cloudflarestorage.com/bucket/key)
  if (trimmed.includes('.r2.cloudflarestorage.com')) {
    const parts = trimmed.split('.r2.cloudflarestorage.com/');
    if (parts.length > 1) {
      // Remove bucket name prefix (e.g. "shopsilo/users/..." -> "users/...")
      const pathWithBucket = parts[1];
      const cleanKey = pathWithBucket.replace(/^[^/]+\//, '');
      return `${API_BASE_URL}/images/${cleanKey}`;
    }
  }

  // Relative paths generated by backend
  if (trimmed.startsWith('/images/')) {
    return `${API_BASE_URL}${trimmed}`;
  }
  if (trimmed.startsWith('images/')) {
    return `${API_BASE_URL}/${trimmed}`;
  }

  // Paths starting with bucket prefix (e.g. shopsilo/users/...)
  if (trimmed.startsWith('shopsilo/')) {
    const cleanKey = trimmed.replace(/^shopsilo\//, '');
    return `${API_BASE_URL}/images/${cleanKey}`;
  }
  if (trimmed.startsWith('/shopsilo/')) {
    const cleanKey = trimmed.replace(/^\/shopsilo\//, '');
    return `${API_BASE_URL}/images/${cleanKey}`;
  }

  // Bare folder paths (e.g. users/..., shops/..., products/...)
  if (trimmed.startsWith('users/') || trimmed.startsWith('shops/') || trimmed.startsWith('products/')) {
    return `${API_BASE_URL}/images/${trimmed}`;
  }
  if (trimmed.startsWith('/users/') || trimmed.startsWith('/shops/') || trimmed.startsWith('/products/')) {
    return `${API_BASE_URL}/images${trimmed}`;
  }

  return trimmed;
};
